title: "David Pugmire"
subtitle: "Distinguished Scientist, Oak Ridge National Laboratory"
baseurl: ""
url: "https://<YOUR_GITHUB_USERNAME>.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Header Navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Publications"
    url: /publications
  - title: "Talks"
    url: /talks

# SEO
author:
  name: "David Pugmire"
  url: "https://<YOUR_GITHUB_USERNAME>.github.io"
  email: ""

# Build
markdown: kramdown
